### ISSUE TITLE
How can I add extra classes for dropdown?

### ISSUE THREAD

**Issue by leecollings** [AlexWebLab/bootstrap-5-wordpress-navbar-walker#1]
I need to add a class to make  a dropdown menu become right aligned, as per the Bootstrap instructions: https://getbootstrap.com/docs/5.0/components/dropdowns/#menu-alignment

The only way I can set this in Wordpress, is to add a class of 'dropdown-menu-end' to the parent menu item. This needs to be passed through to the dropdown though, but it's not.

How would this be possible to set the alignment of the dropdown menu (aside from CSS hacks)?

**Comment by AlexWebLab** [comment]
I just released a new version that adds support for dropdown menu (responsive) alignment: https://github.com/AlexWebLab/bootstrap-5-wordpress-navbar-walker/releases/tag/v1.3.0

Here is how it works:
if one (or more) class(es) related to dropdown responsive alignment (dropdown-menu-{breakpoint}-{start|end}) are detected, then are added to the class list of the .dropdown-menu element.
