### ISSUE TITLE
Show 3rd level items under 2nd level

### ISSUE THREAD

**Issue by wahyutaufik** [AlexWebLab/bootstrap-5-wordpress-navbar-walker#11]
I use for 2 level menu, all is fine. But when I use the 3 level menu, the menu on the third level doesn't appear, but the elements are visible when inspected. And I changed the depth to 3, but it doesn't show up either. 
Can anyone help me?

**Comment by craftwerkberlin** [comment]
Bootstrap has no 3rd level. If you want to show more depth in your menu, you can use this example https://bootstrap-menu.com/detail-multilevel.html

**Comment by wahyutaufik** [comment]
Thank you. This is really helpful
