### ISSUE TITLE
2nd level submenu not working

### ISSUE THREAD

**Issue by sanaazmeh** [AlexWebLab/bootstrap-5-wordpress-navbar-walker#13]
Hi
Thank you for bootstrap walker update.
When i make 2 level submenu it the submenu at level 0  stops working.
Please help.
Thanks.
Sana

**Comment by AlexWebLab** [comment]
Hello, 2nd level submenu is currently not supported by Bootstrap 5 (unless my eyes are missing something obvious!). The goal of this nav walker is to be compatible with Bootstrap 5 and not for all the cases that might arise with the WordPress menu.
