### ISSUE TITLE
Wordpress 5.8

### ISSUE THREAD

**Issue by McHeadCZ** [AlexWebLab/bootstrap-5-wordpress-navbar-walker#17]
Hi! I am not able to get menu in WP 5.8. Does that work for you?
I see that there were done some changes in new version of wordpress.

**Comment by crftwrk** [comment]
In my case walker works fine with 5.8 and I do not see any changes in menu handling in this version?

**Comment by AlexWebLab** [comment]
It works fine for me. Try with this theme: https://github.com/AlexWebLab/barely-minimum-bootstrap-5-wordpress-starter-theme and check the code internally to see how to add a menu.

**Comment by McHeadCZ** [comment]
I made it working! Thank you for help!
