### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by asifpix** [AlexWebLab/bootstrap-5-wordpress-navbar-walker#3]
Hi,

First of all thanks for the nice walker. I have used it in my WordPress theme and when I went to validate my site it gets validation error duplicate attributes. That is why it I came here to let you know.

When your menu depth is higher than 0 then it will get validation error.

Best Regards

**Comment by AlexWebLab** [comment]
Hello there,
Thank you for your feedback. I never heard of this kind of error. Can you help me to reproduce the error? If you tell me the exact steps I can fix it. If you have an online example it would be even better. Thanks.

**Comment by asifpix** [comment]
Hi Alex,

First of create a menu which has sub menu item or dropdown item in **Appearance > Menus**
By creating a dropdown menu using your walker it will output two class. One is **class = "dropdown-item"** and another one is **class = "nav-link"**
But it should be output in a single class like this **class = "dropdown-item nav-link"**
![Screenshot_1](https://user-images.githubusercontent.com/1771011/116866007-7e27ad00-ac2c-11eb-99f3-09e99c5da7a7.png)

I have fixed the error though. If you wish I can send a pull request of this fix.

Best Regards
Asif

**Comment by AlexWebLab** [comment]
Oh yeah I can see that now. I have an idea on how to fix it but I'm curious to see also your solution. Feel free to send a pull request. Thanks.

**Comment by asifpix** [comment]
Thanks Alex, I have sent a pull request.
Best Regards

**Comment by AlexWebLab** [comment]
Thank you Asif, I've merged your pull request and fixed some class name conflicts.

**Comment by asifpix** [comment]
You are most welcome Alex. Stay fine.
