### ISSUE TITLE
JC Submenu not working

### ISSUE THREAD

**Issue by im-mike** [AlexWebLab/bootstrap-5-wordpress-navbar-walker#5]
Hello

Many thanks for this code.

Would you be able to add support for the JC Submenu plugin please?
For some reason it just doesn't show the submenus when I choose to use your walker nav but it (the JC plugin) works if I use it with the regular Wordpress menu (checked with WordPress 5.7.2).

Link to the plugin:
https://wordpress.org/plugins/jc-submenu/

Thank you!

**Comment by AlexWebLab** [comment]
Hello, 
Can you give me a step by step guide on how to reproduce the unexpected behaviour? I'm asking because there might be 100 different use cases for this plugin and then I might have a look and fix 99 of them and then your case might be the exact 1 left out.
Thanks.

**Comment by im-mike** [comment]
Thanks for your reply.

Sure, there you go:
1. Install your walker nav.
2. Install and activate this plugin https://wordpress.org/plugins/jc-submenu/
3. Add a few post categories.
4. Create a new nav menu (under Appearance).
5. Add any link to the menu, click on it to expand, check the "JC Submenu - Automatically populate submenu" checkbox, click "Populate from taxonomy", from Taxonomies dropdown select "category", leave other dropdowns as is (Terms->All...).
6. Click "Save Menu" button.
7. Make sure to display this menu somewhere in you template.
8. The link you've added should have a dropdown with your categories from step 3.

If you just switch the menu from your walker menu to a default Wordpress one, you will see that a dropdown is added, like below:
![image](https://user-images.githubusercontent.com/53824760/119518973-ede31080-bd70-11eb-86b4-3fcd8c510f45.png)

Thank you!

**Comment by AlexWebLab** [comment]
This nav walker supports only Bootstrap 5 and no other plugin/menu.
