### ISSUE TITLE
Is this walker embeddable in other projects?

### ISSUE THREAD

**Issue by stefanobartoletti** [AlexWebLab/bootstrap-5-wordpress-navbar-walker#8]
Hi, I was looking for a Bootstrap 5 nav walker and I stumbled in this library of yours.

I've created a WordPress starter theme that natively integrates Bootstrap, and I'm currently migrating it from BS v.4 to v.5.

I was wondering if it would be possible for me to test your walker and see if it could be embedded in my project. Currently I'm using [wp-bootstrap-nav-walker](https://github.com/wp-bootstrap/wp-bootstrap-navwalker), but it does not support Bootstrap 5, and I'm considering alternatives.

My theme is called [Bricks](https://github.com/stefanobartoletti/bricks), and it is publicly available as an open-source project.

**Comment by AlexWebLab** [comment]
Yes, you can! Just follow any updates or fix I might apply to it. 
“Nulla si crea e nulla si distrugge. Tutto si copia e incolla”.
