### ISSUE TITLE
Adding custom classes to the Anchor elements

### ISSUE THREAD

**Issue by Nite01** [AlexWebLab/bootstrap-5-wordpress-navbar-walker#9]
In my use case I need to be able to add custom classes to the anchor elements created by wp_nav_menu .
To do so, I have a hook filter that should be called on nav_menu_link_attributes.
The problem is that bootstrap_5_wp_nav_menu_walker appears to never call nav_menu_link_attributes, so this does not work. Can this be added ?

I have another similar filter for nav_menu_css_class (used to add classes to the li elements), which works fine (I guess because nav_menu_css_class is actually called in bootstrap_5_wp_nav_menu_walker).

Thanks

**Comment by facundomontiel** [comment]
Hey! Just checking if there are any updates to this thread, as I am currently having the same issue. Did you manage to fix it somehow?

**Comment by Nite01** [comment]
> Hey! Just checking if there are any updates to this thread, as I am currently having the same issue. Did you manage to fix it somehow?

No, but in my case I "solved" the problem by assigning the classes to the < li > elements (using the nav_menu_css_class filter).
If you need help setting that up, let me know and I'll put it here.

**Comment by AlexWebLab** [comment]
Hello guys, sorry I’m little busy these days. I’ll try to look into this and add this functionality inside a couple of weeks. Thanks for your patience. Feel free to pull request in case any of you is faster than me.

**Comment by imranhwebdev** [comment]
Multi Dropdown Not Working, Please Fix This Issue

**Comment by 24Degrees** [comment]
It’s not designed to be multilevel!!

Michaël Martens
24degrees

**Comment by crftwrk** [comment]
Bootstrap has only 2 level depth. But you can code your own https://bootstrap-menu.com
